swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /derechos-pecuniarios/conceptos:
    post:
      tags:
      - derechos-pecuniarios
      description: Agregar un concepto
      operationId: DerechosPecuniariosController.PostConcepto
      parameters:
      - in: body
        name: body
        description: body Agregar Concepto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
  /derechos-pecuniarios/conceptos/{id}:
    put:
      tags:
      - derechos-pecuniarios
      description: Modificar un concepto
      operationId: DerechosPecuniariosController.PutConcepto
      parameters:
      - in: body
        name: body
        description: body Modificar Concepto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
        "403":
          description: :id is empty
        "404":
          description: no data found
    delete:
      tags:
      - derechos-pecuniarios
      description: Inactivar Concepto y Factor por id
      operationId: DerechosPecuniariosController.DeleteConcepto
      parameters:
      - in: path
        name: id
        description: Id del Concepto
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "403":
          description: :id is empty
  /derechos-pecuniarios/conceptos/costo:
    post:
      tags:
      - derechos-pecuniarios
      description: Añadir el costo de un concepto existente
      operationId: DerechosPecuniariosController.PutCostoConcepto
      parameters:
      - in: body
        name: body
        description: body Inhabilitar Proyecto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: :body is empty
  /derechos-pecuniarios/derechos:
    post:
      tags:
      - derechos-pecuniarios
      description: Generar un recibo de derecho pecuniario por parte de estudiantes
      operationId: DerechosPecuniariosController.PostGenerarrDerechoPecuniarioEstudiante
      parameters:
      - in: body
        name: body
        description: body Clonar Conceptos content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
        "404":
          description: not found resource
  /derechos-pecuniarios/personas/{persona_id}:
    get:
      tags:
      - derechos-pecuniarios
      description: get información del estudainte por el id de tercero
      operationId: DerechosPecuniariosController.GetConsultarPersona
      parameters:
      - in: path
        name: persona_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /derechos-pecuniarios/personas/{persona_id}/periodos/{id_periodo}/estados_recibos:
    get:
      tags:
      - derechos-pecuniarios
      description: consultar los estados de todos los recibos de derechos pecuniarios generados por el tercero
      operationId: DerechosPecuniariosController.GetEstadoRecibo
      parameters:
      - in: path
        name: persona_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      - in: path
        name: id_periodo
        description: Id del ultimo periodo
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /derechos-pecuniarios/solicitudes:
    get:
      tags:
      - derechos-pecuniarios
      description: Obtener todos las solicitudes de derechos pecuniarios
      operationId: DerechosPecuniariosController.GetSolicitudDerechoPecuniario
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
    post:
      tags:
      - derechos-pecuniarios
      description: Crear una solicitud de derecho pecuniario
      operationId: DerechosPecuniariosController.PostSolicitudDerechoPecuniario
      parameters:
      - in: body
        name: body
        description: body Agregar Concepto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
  /derechos-pecuniarios/solicitudes/{id}/respuesta:
    post:
      tags:
      - derechos-pecuniarios
      description: Da respuesta a la solicitud de derechos pecuniarios
      operationId: DerechosPecuniariosController.PostRespuestaSolicitudDerechoPecuniario
      parameters:
      - in: path
        name: id
        description: Id de la solicitud
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
  /derechos-pecuniarios/vigencias/{id}:
    get:
      tags:
      - derechos-pecuniarios
      description: Consulta los derechos pecuniarias de la vigencia por id
      operationId: DerechosPecuniariosController.GetDerechosPecuniariosPorVigencia
      parameters:
      - in: path
        name: id
        description: Id de la vigencia correspondiente
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "403":
          description: :id is empty
        "404":
          description: no data found
  /derechos-pecuniarios/vigencias/clonar_conceptos:
    post:
      tags:
      - derechos-pecuniarios
      description: Clona los conceptos de la vigencia anterior en la vigencia actual
      operationId: DerechosPecuniariosController.PostClonarConceptos
      parameters:
      - in: body
        name: body
        description: body Clonar Conceptos content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: body is empty
definitions:
  '{}':
    title: '{}'
    type: object
